### ISSUE TITLE
無法登錄帳號

### ISSUE THREAD

**Issue by ZJUGuoShuai** [zhanglintc/wb#1]
```
bad username or password, please try again!
```
帳號密碼都正確也會報錯。此項目已經不適用了嗎？

**Comment by zhanglintc** [comment]
现在是这样的, 直接使用 `wb -a` 的确是无法登陆的. 如果你的环境可以调用浏览器, 可以尝试 `wb -a m`, 这样会调用默认浏览器访问微博, 得到一个 token, 然后你粘贴回来, 可以登陆.

想实现完全不用外部浏览器直接给定帐号密码就登陆现在已经比较困难了. 我去稍微改一下使用说明.

**Comment by ZJUGuoShuai** [comment]
好的，感謝。
